{
  "contest": 302,
  "handle": "Drynooo",
  "risk": "3",
  "title": "Re-entry vulnerability in the burnToMint function",
  "issueId": 645,
  "issueUrl": "https://github.com/code-423n4/2023-10-nextgen-findings/issues/645"
}